---
language: node_js
node_js:
  - "4.3.2"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower

install:
  - npm install
  - npm install phantomjs-prebuilt
  - bower install

script:
  - npm run check-style
  - npm test
