---
language: node_js
node_js:
  - "lts/boron"

sudo: false
dist: trusty

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache # includes bowers cache

before_script:
  - yarn add global bower
  - bower install
