---
language: node_js
node_js: lts/boron

sudo: false
dist: trusty

env:
  global:
  - SUPPRESS_NO_CONFIG_WARNING=true

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache # includes bowers cache

install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn install --prefer-offline --pure-lockfile
- ./node_modules/bower/bin/bower install --config.interactive=false

script:
- yarn test
