ARG BASE_IMAGE=quay.io/centerforopenscience/ember-osf-registries:develop-development-local

FROM ${BASE_IMAGE} AS base

FROM node:8-alpine AS dist

RUN mkdir -p /code

WORKDIR /code

COPY --from=base /code/dist /code/dist
