
######## ember-osf settings ########
local:
   CLIENT_ID: d29ecabda0ce4b09b9873c9e9b6174c3
   PERSONAL_ACCESS_TOKEN: 227jZZbdqVaIMwCONUVryQUb51vaPlepmGG0uBc9
   OAUTH_SCOPES: osf.full_read osf.full_write

# stage:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write

# stage2:
#   CLIENT_ID: null
#   PERSONAL_ACCESS_TOKEN: null
#   OAUTH_SCOPES: osf.full_read osf.full_write

test:
  CLIENT_ID: 97660c02cc4847a6a048c676fb5f4491
  PERSONAL_ACCESS_TOKEN: lJijX7Tm3UJHu6Bb1diZvZeDqBgW7iV4NrYndbgn
  OAUTH_SCOPES: osf.full_read osf.full_write
######### end ember-osf ##########
