
######## ember-osf settings ########
local:
    CLIENT_ID: null
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://localhost:5000/register/?next=%2Fpreprints%2F
stage:
    CLIENT_ID: null
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: null
    REDIRECT_URI: https://staging.osf.io/register/?next=%2Fpreprints%2F
stage2:
    CLIENT_ID: null
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: null
    REDIRECT_URI: https://staging2.osf.io/register/?next=%2Fpreprints%2F
test:
    CLIENT_ID: null
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: null
    REDIRECT_URI: https://test.osf.io/register/?next=%2Fpreprints%2F
prod:
    CLIENT_ID: null
    PERSONAL_ACCESS_TOKEN: null
    OAUTH_SCOPES: null
    REDIRECT_URI: https://osf.io/register/?next=2Fpreprints%2F
######### end ember-osf ##########
