name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - 'release/*'
      - 'hotfix/*'
env:
  CI: true

jobs:
  fetch-dependencies:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - name: fetch and cache npm dependencies
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: cached_node_modules_${{ hashFiles('**/yarn.lock') }}
        restore-keys: cached_node_modules_
    - if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn --prefer-offline --frozen-lockfile --ignore-engines

  test-with-coverage:
    runs-on: ubuntu-latest
    needs: fetch-dependencies
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: cached_node_modules_${{ hashFiles('**/yarn.lock') }}
        restore-keys: cached_node_modules_

    - run: yarn bower install --config.interactive=false
    - run: yarn test:cover
    - name: Send coverage report to coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
